development:
  adapter: postgresql
  encoding: unicode
  database: motivator_development
  pool: 5
  username: andrewdeitrick
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: motivator_test
  pool: 5
  username: andrewdeitrick
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: motivator_production
  pool: 5
  username: andrewdeitrick
  password:
